/* Generated by MyraPad at 2026/4/27 20:47:35 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace BladeStory.UI.Screen
{
	partial class MainMenu: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Blade Story";
			label1.TextColor = Color.Orange;
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label1.Scale = new Vector2(4, 4);

			_menuNewGame = new MenuItem();
			_menuNewGame.Text = "New Game";
			_menuNewGame.Id = "_menuNewGame";

			_menuLoadGame = new MenuItem();
			_menuLoadGame.Text = "Load Game";
			_menuLoadGame.Id = "_menuLoadGame";

			_menuOptions = new MenuItem();
			_menuOptions.Text = "Options";
			_menuOptions.Id = "_menuOptions";

			_menuQuit = new MenuItem();
			_menuQuit.Text = "Quit";
			_menuQuit.Id = "_menuQuit";

			var verticalMenu1 = new VerticalMenu();
			verticalMenu1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalMenu1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			verticalMenu1.Scale = new Vector2(2, 2);
			verticalMenu1.Items.Add(_menuNewGame);
			verticalMenu1.Items.Add(_menuLoadGame);
			verticalMenu1.Items.Add(_menuOptions);
			verticalMenu1.Items.Add(_menuQuit);

			
			Widgets.Add(label1);
			Widgets.Add(verticalMenu1);
		}

		
		public MenuItem _menuNewGame;
		public MenuItem _menuLoadGame;
		public MenuItem _menuOptions;
		public MenuItem _menuQuit;
	}
}
